#!/usr/bin/env bash
set -euo pipefail

export PATH="$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"

: "${GH_TOKEN:?GH_TOKEN required}"
: "${PR_NUMBER:?PR_NUMBER required}"
: "${REVIEW_CONTEXT_PATH:?REVIEW_CONTEXT_PATH required}"

if [ ! -f "$REVIEW_CONTEXT_PATH" ]; then
  echo "✗ Review context not found: $REVIEW_CONTEXT_PATH" >&2
  exit 1
fi

if ! command -v claude >/dev/null 2>&1; then
  echo "✗ claude CLI not found in PATH" >&2
  exit 1
fi

WORK_DIR=$(mktemp -d -t ai-review)
trap 'rm -rf "$WORK_DIR"' EXIT

PR_JSON="$WORK_DIR/pr.json"
gh pr view "$PR_NUMBER" --json number,title,body,baseRefName,headRefName,url > "$PR_JSON"

PR_TITLE=$(jq -r .title "$PR_JSON")
PR_BODY=$(jq -r '.body // ""' "$PR_JSON")
PR_URL=$(jq -r .url "$PR_JSON")
PR_BASE=$(jq -r .baseRefName "$PR_JSON")
PR_HEAD=$(jq -r .headRefName "$PR_JSON")

DIFF_FILE="$WORK_DIR/diff.patch"
gh pr diff "$PR_NUMBER" > "$DIFF_FILE"

if [ ! -s "$DIFF_FILE" ]; then
  echo "✗ Empty diff — nothing to review" >&2
  exit 1
fi

echo "Diff size: $(wc -c < "$DIFF_FILE") bytes"

PROMPT_FILE="$WORK_DIR/prompt.md"
{
  echo "你是一位資深軟體工程師，正在 review 以下 Pull Request。請依照 review.md 規範產出中立、建設性、附行數的 review。"
  echo ""
  echo "=== BEGIN review.md (project context) ==="
  cat "$REVIEW_CONTEXT_PATH"
  echo ""
  echo "=== END review.md ==="
  echo ""
  echo "## PR metadata"
  echo "- PR #${PR_NUMBER}: ${PR_TITLE}"
  echo "- Base: ${PR_BASE} ← Head: ${PR_HEAD}"
  echo "- URL: ${PR_URL}"
  echo ""
  echo "## PR description"
  echo "${PR_BODY}"
  echo ""
  echo "=== BEGIN DIFF ==="
  echo '```diff'
  cat "$DIFF_FILE"
  echo '```'
  echo "=== END DIFF ==="
  echo ""
  echo "請依 review.md 的 output format 輸出 review markdown："
  echo "- 直接輸出 markdown 內容，不要包在額外的 code block 裡"
  echo "- 不要任何 preamble 或結語"
  echo "- verdict / findings table / details / positive notes 四段俱全"
  echo "- 最後附上『_Generated by Claude Opus 4.7 with review.md context._』註腳"
} > "$PROMPT_FILE"

echo "Prompt size: $(wc -c < "$PROMPT_FILE") bytes"

REVIEW_OUTPUT="$WORK_DIR/review.md"
claude -p "$(cat "$PROMPT_FILE")" \
  --model claude-opus-4-7 \
  --output-format text \
  > "$REVIEW_OUTPUT"

if [ ! -s "$REVIEW_OUTPUT" ]; then
  echo "✗ Claude returned empty review" >&2
  exit 1
fi

REVIEW_SIZE=$(wc -c < "$REVIEW_OUTPUT")
echo "Review size: $REVIEW_SIZE bytes"

if [ "$REVIEW_SIZE" -gt 65000 ]; then
  echo "⚠ Review exceeds GitHub comment limit (65536) — truncating" >&2
  head -c 64500 "$REVIEW_OUTPUT" > "$WORK_DIR/review.trunc.md"
  printf '\n\n_[Review truncated — full version in Actions log]_\n' >> "$WORK_DIR/review.trunc.md"
  mv "$WORK_DIR/review.trunc.md" "$REVIEW_OUTPUT"
fi

gh pr comment "$PR_NUMBER" --body-file "$REVIEW_OUTPUT"
echo "✓ Review posted to PR #${PR_NUMBER}"

if [ -n "${DISCORD_WEBHOOK_URL:-}" ] && [ -n "${DISCORD_USER_ID:-}" ]; then
  MSG="<@${DISCORD_USER_ID}> PR #${PR_NUMBER} AI review 完成，去 GitHub 看 → ${PR_URL}"
  jq -n --arg content "$MSG" --arg uid "$DISCORD_USER_ID" \
    '{content: $content, allowed_mentions: {users: [$uid]}}' | \
    curl -sS -X POST "$DISCORD_WEBHOOK_URL" \
      -H "Content-Type: application/json" \
      --data @- > /dev/null
  echo "✓ Discord notification sent"
fi
