#!/usr/bin/env bash
#
# ai-review.sh — headless AI code review on a PR.
#
# Called from `.github/workflows/review.yml`. Builds a prompt from REVIEW.md
# + PR metadata + diff, runs the `claude` CLI (Sonnet by default, Opus for
# security-critical PRs), posts the result as a single PR comment, and
# notifies Discord if configured.
#
# Required env:
#   GH_TOKEN              GitHub token (BOT_PAT or GITHUB_TOKEN)
#   PR_NUMBER             PR to review
#   REVIEW_CONTEXT_PATH   Path to REVIEW.md (default: REVIEW.md at repo root)
#   CLAUDE_CODE_OAUTH_TOKEN  Claude Code OAuth token
#
# Optional env:
#   CLAUDE_MODEL          Override model (default: sonnet)
#   DISCORD_WEBHOOK_URL   Discord webhook for completion notification
#   DISCORD_USER_ID       Discord user ID to @-mention
#   DIFF_MAX_BYTES        Cap diff size in the prompt (default: 300000)

set -euo pipefail

export PATH="$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"

: "${GH_TOKEN:?GH_TOKEN required}"
: "${PR_NUMBER:?PR_NUMBER required}"
: "${CLAUDE_CODE_OAUTH_TOKEN:?CLAUDE_CODE_OAUTH_TOKEN required}"

REVIEW_CONTEXT_PATH="${REVIEW_CONTEXT_PATH:-REVIEW.md}"
CLAUDE_MODEL="${CLAUDE_MODEL:-sonnet}"
DIFF_MAX_BYTES="${DIFF_MAX_BYTES:-300000}"

if [ ! -f "$REVIEW_CONTEXT_PATH" ]; then
  echo "✗ Review context not found: $REVIEW_CONTEXT_PATH" >&2
  exit 1
fi

if ! command -v claude >/dev/null 2>&1; then
  echo "✗ claude CLI not found in PATH" >&2
  exit 1
fi

# `-t ai-review.XXXXXXXX` works on both GNU (Linux runner) and BSD (macOS)
# mktemp — GNU requires the X's, BSD treats `-t` as a prefix either way.
WORK_DIR=$(mktemp -d -t ai-review.XXXXXXXX)
trap 'rm -rf "$WORK_DIR"' EXIT

# ─── Fetch PR metadata ────────────────────────────────────────────────────
PR_JSON="$WORK_DIR/pr.json"
gh pr view "$PR_NUMBER" --json number,title,body,baseRefName,headRefName,url > "$PR_JSON"

PR_TITLE=$(jq -r .title "$PR_JSON")
PR_BODY=$(jq -r '.body // ""' "$PR_JSON")
PR_URL=$(jq -r .url "$PR_JSON")
PR_BASE=$(jq -r .baseRefName "$PR_JSON")
PR_HEAD=$(jq -r .headRefName "$PR_JSON")

# ─── Fetch diff ───────────────────────────────────────────────────────────
DIFF_FILE="$WORK_DIR/diff.patch"
gh pr diff "$PR_NUMBER" > "$DIFF_FILE"

if [ ! -s "$DIFF_FILE" ]; then
  echo "✗ Empty diff — nothing to review" >&2
  exit 1
fi

DIFF_SIZE=$(wc -c < "$DIFF_FILE")
echo "Diff size: ${DIFF_SIZE} bytes"

# Truncate the diff if it exceeds the configured cap. Prompts beyond ~300KB
# blow up cost AND tend to make the reviewer skim — better to be honest about
# the limit and ask the reviewer to focus on the visible portion.
if [ "$DIFF_SIZE" -gt "$DIFF_MAX_BYTES" ]; then
  echo "⚠ Diff exceeds ${DIFF_MAX_BYTES} bytes — truncating for the prompt"
  head -c "$DIFF_MAX_BYTES" "$DIFF_FILE" > "$WORK_DIR/diff.trunc.patch"
  printf '\n\n[diff truncated — original was %s bytes]\n' "$DIFF_SIZE" >> "$WORK_DIR/diff.trunc.patch"
  mv "$WORK_DIR/diff.trunc.patch" "$DIFF_FILE"
fi

# ─── Build prompt ─────────────────────────────────────────────────────────
PROMPT_FILE="$WORK_DIR/prompt.md"
{
  echo "# Persona override (HIGHEST PRIORITY)"
  echo ""
  echo "你是一位資深軟體工程師，正在為外部讀者（協作者、面試官、未來維護者）"
  echo "做 code review。請套用以下規則："
  echo ""
  echo "- 不使用人格 / 角色聲音。"
  echo "- 全程繁體中文輸出（技術 identifier 保留原文）。"
  echo "- 嚴禁日文混雜、嚴禁中英混雜寫作（除技術術語）。"
  echo "- 不要 emoji 當情緒裝飾；嚴重度 emoji（🔴 🟡 🟣）保留——它們是 tag。"
  echo "- 不要「我覺得」「我們可以」這種開場小聊；用證據導向、引用 file:line 的敘述。"
  echo "- 每個 finding 必須引用 file_path:line_number。"
  echo ""
  echo "---"
  echo ""
  echo "# REVIEW.md (project review override)"
  echo ""
  cat "$REVIEW_CONTEXT_PATH"
  echo ""
  echo "---"
  echo ""
  echo "# PR metadata"
  echo "- PR #${PR_NUMBER}: ${PR_TITLE}"
  echo "- Base: ${PR_BASE} ← Head: ${PR_HEAD}"
  echo "- URL: ${PR_URL}"
  echo ""
  echo "## PR description"
  echo ""
  echo "${PR_BODY}"
  echo ""
  echo "---"
  echo ""
  echo "# Diff to review"
  echo ""
  echo '```diff'
  cat "$DIFF_FILE"
  echo '```'
  echo ""
  echo "---"
  echo ""
  echo "# Output instructions"
  echo ""
  echo "依 REVIEW.md → 「Output format」 輸出 review markdown："
  echo "- 直接輸出 markdown 內容（不要包在 code block 裡）。"
  echo "- 不要 preamble、不要結語。"
  echo "- 必含：verdict 行、findings table、Top 3 concerns、Details、optional Positive notes。"
  echo "- 最後一行附註：\`_Generated by Claude (${CLAUDE_MODEL}) with REVIEW.md context._\`"
} > "$PROMPT_FILE"

echo "Prompt size: $(wc -c < "$PROMPT_FILE") bytes"

# ─── Run claude ───────────────────────────────────────────────────────────
# Prompt goes via stdin, NOT argv — a large diff (e.g. a migration PR's
# ~300KB prompt) blows past ARG_MAX and fails with "Argument list too
# long" (exit 126) if passed as an argument.
REVIEW_OUTPUT="$WORK_DIR/review.md"
claude -p \
  --model "$CLAUDE_MODEL" \
  --output-format text \
  < "$PROMPT_FILE" \
  > "$REVIEW_OUTPUT"

if [ ! -s "$REVIEW_OUTPUT" ]; then
  echo "✗ Claude returned empty review" >&2
  exit 1
fi

REVIEW_SIZE=$(wc -c < "$REVIEW_OUTPUT")
echo "Review size: ${REVIEW_SIZE} bytes"

# GitHub comment size limit: 65536 chars. Truncate to leave headroom.
if [ "$REVIEW_SIZE" -gt 65000 ]; then
  echo "⚠ Review exceeds GitHub comment limit (65536) — truncating"
  head -c 64500 "$REVIEW_OUTPUT" > "$WORK_DIR/review.trunc.md"
  printf '\n\n_[Review truncated — full version in Actions log]_\n' >> "$WORK_DIR/review.trunc.md"
  mv "$WORK_DIR/review.trunc.md" "$REVIEW_OUTPUT"
fi

# ─── Post comment + set verdict label ─────────────────────────────────────
gh pr comment "$PR_NUMBER" --body-file "$REVIEW_OUTPUT"
echo "✓ Review posted to PR #${PR_NUMBER}"

# Parse verdict line and set the matching label. Tolerate variations:
#   **Verdict:** pass
#   Verdict: changes-requested
VERDICT=$(grep -ioE 'verdict[: *]+[*]*[ ]*(pass|changes-requested|human-needed)' "$REVIEW_OUTPUT" | head -1 | grep -ioE '(pass|changes-requested|human-needed)' || echo "")

case "$VERDICT" in
  pass)
    gh api -X POST "repos/${GITHUB_REPOSITORY:-$(gh repo view --json nameWithOwner --jq .nameWithOwner)}/issues/${PR_NUMBER}/labels" \
      --input - <<<'{"labels":["review/pass"]}' >/dev/null 2>&1 || true
    echo "✓ Labelled review/pass"
    ;;
  changes-requested)
    gh api -X POST "repos/${GITHUB_REPOSITORY:-$(gh repo view --json nameWithOwner --jq .nameWithOwner)}/issues/${PR_NUMBER}/labels" \
      --input - <<<'{"labels":["ai-fix"]}' >/dev/null 2>&1 || true
    echo "✓ Labelled ai-fix"
    ;;
  *)
    echo "::warning::Could not parse verdict from review output — no label set"
    ;;
esac

# ─── Discord notification (optional) ──────────────────────────────────────
if [ -n "${DISCORD_WEBHOOK_URL:-}" ] && [ -n "${DISCORD_USER_ID:-}" ]; then
  MSG="<@${DISCORD_USER_ID}> PR #${PR_NUMBER} AI review 完成（verdict: ${VERDICT:-unknown}）→ ${PR_URL}"
  jq -n --arg content "$MSG" --arg uid "$DISCORD_USER_ID" \
    '{content: $content, allowed_mentions: {users: [$uid]}}' | \
    curl -sS -X POST "$DISCORD_WEBHOOK_URL" \
      -H "Content-Type: application/json" \
      --data @- > /dev/null
  echo "✓ Discord notification sent"
fi
