/**
 * Named type aliases over the generated `types.ts`.
 *
 * Downstream code should import from "@/lib/api" (this file) rather than
 * reaching into `components["schemas"]["..."]` directly — it's shorter and
 * re-homing a type (e.g. renaming a backend schema) only needs a change
 * here, not across every Mode A/B/C module.
 *
 * `types.ts` is auto-generated by `bun run gen:types`. Do not edit it.
 * Add named aliases here as new schemas land.
 */
import type { components, paths } from "./types";

type S = components["schemas"];

// Anchors (stations)
export type Anchor = S["AnchorOut"];
export type AnchorCreate = S["AnchorCreate"];
export type AnchorUpdate = S["AnchorUpdate"];
export type WorldPose = S["WorldPose"];

// Objects (ar_objects)
export type ARObject = S["ARObjectOut"];
export type ARObjectCreate = S["ARObjectCreate"];
export type ARObjectUpdate = S["ARObjectUpdate"];

// Placements
export type Placement = S["PlacementOut"];
export type PlacementCreate = S["PlacementCreate"];
export type PlacementUpdate = S["PlacementUpdate"];
export type Transform = S["Transform"];
export type UVTransform = S["UVTransform"];

// Geometry — defined once in the backend's `common.schemas` and emitted
// as unqualified `Vec3` / `Quat` in OpenAPI, so the frontend consumes the
// same shapes anchors and placements use.
export type Vec3 = S["Vec3"];
export type Quat = S["Quat"];

// Textures
export type UploadURLRequest = S["UploadURLRequest"];
export type UploadURLResponse = S["UploadURLResponse"];

// Useful when writing fetch helpers against specific endpoints.
export type { components, paths };
