/**
 * Named type aliases over the generated `types.ts`.
 *
 * Downstream code should import from "@/lib/api" (this file) rather than
 * reaching into `components["schemas"]["..."]` directly — it's shorter and
 * re-homing a type (e.g. renaming a backend schema) only needs a change
 * here, not across every Mode A/B/C module.
 *
 * `types.ts` is auto-generated by `bun run gen:types`. Do not edit it.
 * Add named aliases here as new schemas land.
 */
import type { components, paths } from "./types";

type S = components["schemas"];

// Anchors (stations)
export type Anchor = S["AnchorOut"];
export type AnchorCreate = S["AnchorCreate"];
export type AnchorUpdate = S["AnchorUpdate"];
export type WorldPose = S["WorldPose"];

// Objects (ar_objects)
export type ARObject = S["ARObjectOut"];
export type ARObjectCreate = S["ARObjectCreate"];
export type ARObjectUpdate = S["ARObjectUpdate"];

// Placements
export type Placement = S["PlacementOut"];
export type PlacementCreate = S["PlacementCreate"];
export type PlacementUpdate = S["PlacementUpdate"];
export type Transform = S["Transform"];
export type UVTransform = S["UVTransform"];
export type Quat = S["Quat"];
// Vec3 is inlined by openapi-typescript (it's a trivial shape without validators);
// define a hand-written matching type rather than reaching through the inlined
// `position` / `scale` fields of Transform.
export type Vec3 = { x: number; y: number; z: number };

// Textures
export type UploadURLRequest = S["UploadURLRequest"];
export type UploadURLResponse = S["UploadURLResponse"];

// Useful when writing fetch helpers against specific endpoints.
export type { components, paths };
