/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anchors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Anchors */
        get: operations["list_anchors_api_anchors_get"];
        put?: never;
        /** Create Anchor */
        post: operations["create_anchor_api_anchors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anchors/{anchor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Anchor */
        get: operations["get_anchor_api_anchors__anchor_id__get"];
        put?: never;
        post?: never;
        /** Delete Anchor */
        delete: operations["delete_anchor_api_anchors__anchor_id__delete"];
        options?: never;
        head?: never;
        /** Update Anchor */
        patch: operations["update_anchor_api_anchors__anchor_id__patch"];
        trace?: never;
    };
    "/api/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Objects */
        get: operations["list_objects_api_objects_get"];
        put?: never;
        /** Create Object */
        post: operations["create_object_api_objects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objects/{object_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Object */
        get: operations["get_object_api_objects__object_id__get"];
        put?: never;
        post?: never;
        /** Delete Object */
        delete: operations["delete_object_api_objects__object_id__delete"];
        options?: never;
        head?: never;
        /** Update Object */
        patch: operations["update_object_api_objects__object_id__patch"];
        trace?: never;
    };
    "/api/placements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Placements */
        get: operations["list_placements_api_placements_get"];
        put?: never;
        /** Create Placement */
        post: operations["create_placement_api_placements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/placements/{placement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Placement */
        get: operations["get_placement_api_placements__placement_id__get"];
        put?: never;
        post?: never;
        /** Delete Placement */
        delete: operations["delete_placement_api_placements__placement_id__delete"];
        options?: never;
        head?: never;
        /** Update Placement */
        patch: operations["update_placement_api_placements__placement_id__patch"];
        trace?: never;
    };
    "/api/textures/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Upload Url */
        post: operations["create_upload_url_api_textures_upload_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ARObjectCreate */
        ARObjectCreate: {
            /** Label */
            label: string;
            /** Description */
            description?: string | null;
        };
        /** ARObjectOut */
        ARObjectOut: {
            /** Label */
            label: string;
            /** Description */
            description?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ARObjectUpdate */
        ARObjectUpdate: {
            /** Label */
            label?: string | null;
            /** Description */
            description?: string | null;
        };
        /** AnchorCreate */
        AnchorCreate: {
            /** Label */
            label: string;
            /** Size Mm */
            size_mm: number;
            world_pos?: components["schemas"]["WorldPose"] | null;
        };
        /** AnchorOut */
        AnchorOut: {
            /** Label */
            label: string;
            /** Size Mm */
            size_mm: number;
            world_pos?: components["schemas"]["WorldPose"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AnchorUpdate */
        AnchorUpdate: {
            /** Label */
            label?: string | null;
            /** Size Mm */
            size_mm?: number | null;
            world_pos?: components["schemas"]["WorldPose"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** PlacementCreate */
        PlacementCreate: {
            /**
             * Ar Object Id
             * Format: uuid
             */
            ar_object_id: string;
            /**
             * Anchor Id
             * Format: uuid
             */
            anchor_id: string;
            /** Texture Id */
            texture_id?: string | null;
            transform: components["schemas"]["Transform"];
            uv_transform?: components["schemas"]["UVTransform"] | null;
        };
        /** PlacementOut */
        PlacementOut: {
            /**
             * Ar Object Id
             * Format: uuid
             */
            ar_object_id: string;
            /**
             * Anchor Id
             * Format: uuid
             */
            anchor_id: string;
            /** Texture Id */
            texture_id?: string | null;
            transform: components["schemas"]["Transform"];
            uv_transform?: components["schemas"]["UVTransform"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PlacementUpdate
         * @description PATCH mutates the texture and the local transform only.
         *
         *     `ar_object_id` / `anchor_id` are intentionally omitted: moving a
         *     placement across anchors or to a different object is destructive
         *     enough that it should go through DELETE + POST. Keeps the audit trail
         *     readable.
         *
         *     Null semantics (Pydantic v2 + `exclude_unset=True` in the repository):
         *     - field absent from body → keep current value
         *     - field present as `null` → clear the value (only meaningful for
         *       `texture_id`, which is nullable; null on `transform` /
         *       `uv_transform` is a client bug since those aren't nullable here)
         */
        PlacementUpdate: {
            /** Texture Id */
            texture_id?: string | null;
            transform?: components["schemas"]["Transform"] | null;
            uv_transform?: components["schemas"]["UVTransform"] | null;
        };
        /**
         * Quat
         * @description Unit quaternion in (x, y, z, w) order — matches three.js / R3F.
         */
        Quat: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
            /** W */
            w: number;
        };
        /**
         * Transform
         * @description 3D pose of the object relative to its anchor's local frame.
         *
         *     `scale` components must be strictly positive — mirror / flip is not a
         *     supported admin move for this artwork (spiral metal mesh textures are
         *     directional) and negative values are almost always a client bug. This
         *     matches `UVTransform` so a single rule applies to both transforms.
         */
        Transform: {
            position: components["schemas"]["Vec3"];
            rotation: components["schemas"]["Quat"];
            scale: components["schemas"]["Vec3"];
        };
        /**
         * UVTransform
         * @description 2D adjustment applied to a texture as it maps onto the object's UVs.
         *
         *     `rotate` is in radians (matches three.js Texture.rotation). Mirror /
         *     flip is not supported — zero or negative scale would squash or invert
         *     the UVs and is almost always a client bug.
         */
        UVTransform: {
            /**
             * Scale X
             * @default 1
             */
            scale_x: number;
            /**
             * Scale Y
             * @default 1
             */
            scale_y: number;
            /**
             * Rotate
             * @default 0
             */
            rotate: number;
            /**
             * Offset X
             * @default 0
             */
            offset_x: number;
            /**
             * Offset Y
             * @default 0
             */
            offset_y: number;
        };
        /** UploadURLRequest */
        UploadURLRequest: {
            /** Filename */
            filename: string;
            /** Mime */
            mime: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** UploadURLResponse */
        UploadURLResponse: {
            /** Upload Url */
            upload_url: string;
            /** Storage Path */
            storage_path: string;
            /** Token */
            token: string;
            /** Expires At */
            expires_at: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Vec3
         * @description Right-handed 3D point / vector.
         *
         *     NaN / ±Inf rejected at the boundary — they silently pass through
         *     arithmetic (scale, quaternion magnitude) and leave downstream
         *     renderers with un-drawable transforms.
         */
        Vec3: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
        };
        /**
         * WorldPose
         * @description Anchor's pose relative to the venue origin, if configured.
         *
         *     `rotation` is a unit quaternion in (x, y, z, w) order; the same
         *     convention used by three.js / R3F on the frontend, so values pass
         *     through without transformation.
         */
        WorldPose: {
            position: components["schemas"]["Vec3"];
            rotation: components["schemas"]["Quat"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_anchors_api_anchors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnchorOut"][];
                };
            };
        };
    };
    create_anchor_api_anchors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnchorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnchorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_anchor_api_anchors__anchor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                anchor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnchorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_anchor_api_anchors__anchor_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                anchor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_anchor_api_anchors__anchor_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                anchor_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnchorUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnchorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_objects_api_objects_get: {
        parameters: {
            query?: {
                /** @description Filter to objects placed at the given anchor. 404 if the anchor does not exist. */
                anchor_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ARObjectOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_object_api_objects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ARObjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ARObjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_object_api_objects__object_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ARObjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_object_api_objects__object_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_object_api_objects__object_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ARObjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ARObjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_placements_api_placements_get: {
        parameters: {
            query?: {
                /** @description Filter to placements at the given anchor */
                anchor_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacementOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_placement_api_placements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlacementCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_placement_api_placements__placement_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_placement_api_placements__placement_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_placement_api_placements__placement_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlacementUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_upload_url_api_textures_upload_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadURLRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadURLResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
