/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Single-admin login. Compare email + password against env-configured
         *     values and mint an HS256 JWT.
         *
         *     Returns the spec-shaped 401 ({"detail": "Invalid credentials"}) on any
         *     mismatch — never leaks which of the two fields was wrong.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anchors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Anchors */
        get: operations["list_anchors_anchors_get"];
        put?: never;
        /** Create Anchor */
        post: operations["create_anchor_anchors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anchors/{anchor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Anchor */
        get: operations["get_anchor_anchors__anchor_id__get"];
        put?: never;
        post?: never;
        /** Delete Anchor */
        delete: operations["delete_anchor_anchors__anchor_id__delete"];
        options?: never;
        head?: never;
        /** Update Anchor */
        patch: operations["update_anchor_anchors__anchor_id__patch"];
        trace?: never;
    };
    "/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Objects */
        get: operations["list_objects_objects_get"];
        put?: never;
        /** Create Object */
        post: operations["create_object_objects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/objects/{object_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Object */
        get: operations["get_object_objects__object_id__get"];
        put?: never;
        post?: never;
        /** Delete Object */
        delete: operations["delete_object_objects__object_id__delete"];
        options?: never;
        head?: never;
        /** Update Object */
        patch: operations["update_object_objects__object_id__patch"];
        trace?: never;
    };
    "/placements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Placements */
        get: operations["list_placements_placements_get"];
        put?: never;
        /** Create Placement */
        post: operations["create_placement_placements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/placements/{placement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Placement */
        get: operations["get_placement_placements__placement_id__get"];
        put?: never;
        post?: never;
        /** Delete Placement */
        delete: operations["delete_placement_placements__placement_id__delete"];
        options?: never;
        head?: never;
        /** Update Placement */
        patch: operations["update_placement_placements__placement_id__patch"];
        trace?: never;
    };
    "/textures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Textures */
        get: operations["list_textures_textures_get"];
        put?: never;
        /** Upload Texture */
        post: operations["upload_texture_textures_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/textures/{texture_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Texture */
        get: operations["get_texture_textures__texture_id__get"];
        put?: never;
        post?: never;
        /** Delete Texture */
        delete: operations["delete_texture_textures__texture_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/textures/{texture_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Texture File */
        get: operations["get_texture_file_textures__texture_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ARObjectCreate */
        ARObjectCreate: {
            /** Label */
            label: string;
            /** Description */
            description?: string | null;
        };
        /** ARObjectOut */
        ARObjectOut: {
            /** Label */
            label: string;
            /** Description */
            description?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ARObjectUpdate */
        ARObjectUpdate: {
            /** Label */
            label?: string | null;
            /** Description */
            description?: string | null;
        };
        /** AnchorCreate */
        AnchorCreate: {
            /** Label */
            label: string;
            /** Size Mm */
            size_mm: number;
            world_pos?: components["schemas"]["WorldPose"] | null;
        };
        /** AnchorOut */
        AnchorOut: {
            /** Label */
            label: string;
            /** Size Mm */
            size_mm: number;
            world_pos?: components["schemas"]["WorldPose"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AnchorUpdate */
        AnchorUpdate: {
            /** Label */
            label?: string | null;
            /** Size Mm */
            size_mm?: number | null;
            world_pos?: components["schemas"]["WorldPose"] | null;
        };
        /** Body_upload_texture_textures_post */
        Body_upload_texture_textures_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Label */
            label?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * LoginRequest
         * @description POST /auth/login body.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MeResponse
         * @description GET /auth/me response.
         */
        MeResponse: {
            /** Email */
            email: string;
            /** Is Admin */
            is_admin: boolean;
        };
        /** PlacementCreate */
        PlacementCreate: {
            /**
             * Ar Object Id
             * Format: uuid
             */
            ar_object_id: string;
            /**
             * Anchor Id
             * Format: uuid
             */
            anchor_id: string;
            /** Texture Id */
            texture_id?: string | null;
            transform: components["schemas"]["Transform"];
            uv_transform?: components["schemas"]["UVTransform"] | null;
            /**
             * Is Show
             * @default true
             */
            is_show: boolean;
        };
        /** PlacementOut */
        PlacementOut: {
            /**
             * Ar Object Id
             * Format: uuid
             */
            ar_object_id: string;
            /**
             * Anchor Id
             * Format: uuid
             */
            anchor_id: string;
            /** Texture Id */
            texture_id?: string | null;
            transform: components["schemas"]["Transform"];
            uv_transform?: components["schemas"]["UVTransform"] | null;
            /**
             * Is Show
             * @default true
             */
            is_show: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PlacementUpdate
         * @description PATCH mutates the texture and the local transform only.
         *
         *     `ar_object_id` / `anchor_id` are intentionally omitted: moving a
         *     placement across anchors or to a different object is destructive
         *     enough that it should go through DELETE + POST. Keeps the audit trail
         *     readable.
         */
        PlacementUpdate: {
            /** Texture Id */
            texture_id?: string | null;
            transform?: components["schemas"]["Transform"] | null;
            uv_transform?: components["schemas"]["UVTransform"] | null;
            /** Is Show */
            is_show?: boolean | null;
        };
        /**
         * Quat
         * @description Unit quaternion in (x, y, z, w) order — matches three.js / R3F.
         */
        Quat: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
            /** W */
            w: number;
        };
        /**
         * TextureOut
         * @description Texture row as returned by the API.
         *
         *     `file_url` is a relative URL; the frontend prepends `VITE_API_BASE_URL`
         *     before fetching. Computed from `id` so callers don't construct the
         *     string themselves.
         */
        TextureOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Filename */
            filename: string;
            /** Mime Type */
            mime_type: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** File Url */
            readonly file_url: string;
            /**
             * Kind
             * @description Render-path discriminator for the client: a glTF binary is a 3D
             *     model placed as-is; everything else is a 2D image drawn on a quad.
             *     Derived from the mime type so the client never sniffs bytes.
             */
            readonly kind: string;
        };
        /**
         * TokenResponse
         * @description POST /auth/login 200 response.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /**
         * Transform
         * @description 3D pose of the object relative to its anchor's local frame.
         *
         *     `scale` components must be strictly positive — mirror / flip is not a
         *     supported admin move for this artwork (spiral metal mesh textures are
         *     directional) and negative values are almost always a client bug. This
         *     matches `UVTransform` so a single rule applies to both transforms.
         */
        Transform: {
            position: components["schemas"]["Vec3"];
            rotation: components["schemas"]["Quat"];
            scale: components["schemas"]["Vec3"];
        };
        /**
         * UVTransform
         * @description 2D adjustment applied to a texture as it maps onto the object's UVs.
         *
         *     `rotate` is in radians (matches three.js Texture.rotation). Mirror /
         *     flip is not supported — zero or negative scale would squash or invert
         *     the UVs and is almost always a client bug.
         */
        UVTransform: {
            /**
             * Scale X
             * @default 1
             */
            scale_x: number;
            /**
             * Scale Y
             * @default 1
             */
            scale_y: number;
            /**
             * Rotate
             * @default 0
             */
            rotate: number;
            /**
             * Offset X
             * @default 0
             */
            offset_x: number;
            /**
             * Offset Y
             * @default 0
             */
            offset_y: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Vec3
         * @description Right-handed 3D point / vector.
         *
         *     NaN / ±Inf rejected at the boundary — they silently pass through
         *     arithmetic (scale, quaternion magnitude) and leave downstream
         *     renderers with un-drawable transforms.
         */
        Vec3: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
        };
        /**
         * WorldPose
         * @description Anchor's pose relative to the venue origin, if configured.
         *
         *     `rotation` is a unit quaternion in (x, y, z, w) order; the same
         *     convention used by three.js / R3F on the frontend, so values pass
         *     through without transformation.
         */
        WorldPose: {
            position: components["schemas"]["Vec3"];
            rotation: components["schemas"]["Quat"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_anchors_anchors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnchorOut"][];
                };
            };
        };
    };
    create_anchor_anchors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnchorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnchorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_anchor_anchors__anchor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                anchor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnchorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_anchor_anchors__anchor_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                anchor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_anchor_anchors__anchor_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                anchor_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnchorUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnchorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_objects_objects_get: {
        parameters: {
            query?: {
                /** @description Filter to objects placed at the given anchor. 404 if the anchor does not exist. */
                anchor_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ARObjectOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_object_objects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ARObjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ARObjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_object_objects__object_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ARObjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_object_objects__object_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_object_objects__object_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ARObjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ARObjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_placements_placements_get: {
        parameters: {
            query?: {
                /** @description Filter to placements at the given anchor */
                anchor_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacementOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_placement_placements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlacementCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_placement_placements__placement_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_placement_placements__placement_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_placement_placements__placement_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlacementUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_textures_textures_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextureOut"][];
                };
            };
        };
    };
    upload_texture_textures_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_texture_textures_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextureOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_texture_textures__texture_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                texture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextureOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_texture_textures__texture_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                texture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_texture_file_textures__texture_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                texture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
